[package]
name = "chemical-formula"
version = "0.1.2"
edition = "2021"
authors = ["Ameyanagi <contact@ameyanagi.com>"]
rust-version = "1.83"
description = "Chemical formula parser that can handle wt% and nested structure"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Ameyanagi/chemical-formula-rs"
homepage = "https://github.com/Ameyanagi/chemical-formula-rs/tree/v0.1.1"
documentation = "https://docs.rs/Ameyanagi/chemical-formula/0.1.1"
keywords = ["chemistry", "parser"]
categories = ["science", "parser-implementations"]
readme = "README.md"
include = [
  "**/*.rs",
  "**/*.pest",
  "Cargo.toml",
  "CHANGELOG.md",
  "CODE_OF_CONDUCT.md",
  "COPYRIGHT.md",
  "LICENSE-*",
  "README.md",
  "SECURITY.md",
]
publish = true

[workspace]
members = [".", "bindings/wasm", "bindings/python"]
resolver = "2"

[profile.release]
strip = false

[features]
default = []
serde = ["dep:serde"]

[badges]
is-it-maintained-issue-resolution = { repository = "Ameyanagi/chemical-formula-rs" }
is-it-maintained-open-issues = { repository = "Ameyanagi/chemical-formula-rs" }
maintenance = { status = "experimental" }                                            # This may differ between branches.

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.21.3"
pest = "2.8.6"
pest_derive = "2.8.6"
serde = { version = "1.0.228", features = ["derive"], optional = true }

[dev-dependencies]
approx = "0.5.1"
serde_json = "1.0.149"
