[package]
name = "chemical-formula"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
once_cell = "1.19.0"
pest = "2.7.7"
pest_derive = "2.7.7"
