[package]
name = "chemical-formula-python"
version = "0.1.1"
edition = "2021"
rust-version = "1.83"
authors = ["Ameyanagi <contact@ameyanagi.com>"]
description = "Python bindings for chemical-formula"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Ameyanagi/chemical-formula-rs"
publish = false

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
chemical-formula = { path = "../..", features = ["serde"] }
pyo3 = { version = "0.22.6", features = ["abi3-py39", "extension-module"] }
