formula = { SOI ~ expr* ~ EOI }

element = { element_symbol ~ stoichiometry? }

number         = { ("+" | "-")? ~ ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT+)? }
weight_percent = { number ~ "wt%" }
stoichiometry  = { weight_percent | number }
group          = {
    (("(" ~ expr+ ~ ")") | ("[" ~ expr+ ~ "]") | ("{" ~ expr+ ~ "}")) ~ stoichiometry?
}

separator = _{ " " | "\t" | "." | "@" | "/" | NEWLINE }
expr      = _{ element | group | separator }

element_symbol = @{ ASCII_ALPHA_UPPER ~ ASCII_ALPHA_LOWER? }
